name: Email Enrichment Cron

on:
  schedule:
    # 08:00–18:00 IST (Mon–Fri), every 30 mins
    # 02:30–12:30 UTC (Mon–Fri)
    #- cron: '30 2 * * 1-5'      # 08:00 IST
    #- cron: '0,30 3-12 * * 1-5' # 08:30–18:00 IST
  workflow_dispatch:

jobs:
  enrich-emails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run enrichment script
        run: node enrichEmails.js
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
